pages:
  stage: deploy
  environment: production
  script:
    - mkdir .public
    - cp index.html .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
